In [1]:
import pandas as pd
import pickle
from sklearn import metrics 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold, train_test_split
from numpy import mean, absolute

In [2]:
infile = open('../01_data/FINALsmallSampleSet_3months_without_duplicates.pkl','rb')
df = pickle.load(infile)
infile.close()

In [4]:


infile = open('../01_data/smallSampleSet_3months.pkl','rb')
user = pickle.load(infile)
infile.close()

In [7]:
len(user.UserID.unique())

65361

In [3]:
df

,Erstloesung,Erfolg,Schwierigkeit,Wochentag,ist_Schulzeit,MehrfachFalsch,Testposition__FT,Testposition__nt,Testposition__pruefung,Testposition__training,...,9992992,9992993,9992994,9992995,9992996,9992997,9992998,9992999,9993000,9993001
0,1,0,1.672830,3,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1.082760,2,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,0,-1.629740,0,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,0,1.722470,2,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,0,-0.128691,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,0,1,-1.107240,2,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
199996,1,1,-2.267480,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
199997,1,1,1.141720,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
199998,0,1,2.236460,3,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
199999,1,1,-1.865930,4,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0